### ISSUE TITLE
Helm repository

### ISSUE THREAD

**Issue by treussart** [scaleway/cert-manager-webhook-scaleway#11]
**Is your feature request related to a problem? Please describe.**
I would like to be able to install the chart without having to clone the Git repository.

**Describe the solution you'd like**
It should be made available in a public Helm chart repository.
https://helm.sh/docs/topics/chart_repository/

**Comment by suda** [comment]
Not an ideal solution but I added it to my repo with Helm charts: https://artifacthub.io/packages/helm/suda/scaleway-webhook in case someone else needs to use it

**Comment by 0snap** [comment]
Hi, what's the status here? We'd like to use this and would love to see an official helm repo for installation.

**Comment by Nox-404** [comment]
Done
