### ISSUE TITLE
Certficate requests for domains spanning multiple projects

### ISSUE THREAD

**Issue by mibmo** [scaleway/cert-manager-webhook-scaleway#12]
**Is your feature request related to a problem? Please describe.**
API keys are per-project. Creating certificates for domains managed by different projects isn't straight-forward and impossible if trying to use only one issuer.

**Describe the solution you'd like**
Proper IAM support would be ideal, but that's probably a lot of work. (And not directly related to the webhook: I've created a [feature request](https://feature-request.scaleway.com/posts/460/proper-iam))

**Describe alternatives you've considered**
The ability to specify multiple API keys in the scaleway-secret, and having it find and use the correct one for the domain specified.
It's also possible to create multiple issuers, one for each project, but this adds an extra layer of complexity.

A caveat to _both_ these alternatives is that there'll be SCW credentials to manage what might be a substantial part of your cloud infrastructure just lying around as Kubernetes secrets.

**Additional context**
This has caused a lot of headaches.
What we ended up doing was moving all managed DNS zones to the same project and creating an API key for that, but that's far from ideal and a very hacky and time-consuming solution.

**Comment by Nox-404** [comment]
Hello,
with the current IAM, you can create a dedicated application with a policy with DNS API access to any project you want.
Then use that application's api key in the webhook.

Something like this: 
![image](https://github.com/scaleway/cert-manager-webhook-scaleway/assets/5402193/6103fcdd-cc39-4bcc-90a9-f8de4285fc09)
