### ISSUE TITLE
Helm install fails on latest version

### ISSUE THREAD

**Issue by leinelissen** [scaleway/cert-manager-webhook-scaleway#16]
**Describe the bug**
Running the install command with the current latest commit returns 
```
Error: INSTALLATION FAILED: template: scaleway-webhook/templates/deployment.yaml:23:22: executing "scaleway-webhook/templates/deployment.yaml" at <.Values.server.imagePullSecrets>: nil pointer evaluating interface {}.imagePullSecrets
```

**To Reproduce**
`helm install Scaleway-webhook deploy/scaleway-webhook`

**Expected behavior**
The install command installs the web hook

**Details (please complete the following information):**
 - Scaleway Cert Manager Webhook version: commit `3445b89`
 - Platform: macOS
 - Kubernetes version: v1.27.0

**Additional context**
I pulled a commit before the latest (`d344bee143e3ae9ed173b27769c59efe6b3871c2`) and this one managed to install fine.

**Comment by Sh4d1** [comment]
Hey! My bad I merged too quickly without testing, @leinelissen  could you test with `feb4a2c8cbffcdb4493ae8e9f87a7f3bb2de6701`, should work better ?

**Comment by leinelissen** [comment]
Yeah this one works. cheers!

**Comment by Sh4d1** [comment]
Perfect thanks!
