### ISSUE TITLE
is the project dead ?

### ISSUE THREAD

**Issue by M0NsTeRRR** [scaleway/cert-manager-webhook-scaleway#18]
Hello,

I would like to use cert manager with this webhook as I don't see any commit and with a major issue for my use case #8, is this project is still maintained ? Just asking before writing something :)

Regards,

**Comment by Nox-404** [comment]
Hello,
I took a few minutes to test out #8, I could not reproduce the issue... (you can check out my comment there)
Did you try on your end ?

**Comment by M0NsTeRRR** [comment]
Hello,

Will test out know, but without input from Scaleway team, I will prefer to rebuild the project as some dependencies are really outdated. Will let you know :)

**Comment by M0NsTeRRR** [comment]
As I can see from your comment, it worked on your side because you created a subdomain. When in #8 he didn't. I will try now.

**Comment by M0NsTeRRR** [comment]
Works on my side too @Nox-404 :). Does there any plans to update dependencies project ?

**Comment by Nox-404** [comment]
I'll package it soon with the other charts we have...
Maybe update the deps in the process too

**Comment by M0NsTeRRR** [comment]
Glad to hear that :)

**Comment by M0NsTeRRR** [comment]
Hello @Nox-404,

Any news about this ?

Regards,

**Comment by raskyld** [comment]
I am proceeding with the relicensing of the repository in #19 then I will probably update the project ;)

**Comment by M0NsTeRRR** [comment]
Thanks for your update, will be happy to test it :)

**Comment by 0snap** [comment]
Hi @raskyld, I saw the relicensing is done! Are there any news on the packaging & official helm repo?

**Comment by raskyld** [comment]
Hey, I started a PR bumping and testing the chart, I've been assigned to other stuff but I will try to get back to it soon!
