### ISSUE TITLE
Using deprecated flowcontrol api

### ISSUE THREAD

**Issue by MathyV** [scaleway/cert-manager-webhook-scaleway#22]
**Describe the bug**
After applying the extra role as described in #21 I still get errors because now it can search for the resources but they are not actually present in the cluster.
```
go@v0.20.0/tools/cache/reflector.go:167: Failed to watch *v1beta1.PriorityLevelConfiguration: failed to list *v1beta1.PriorityLevelConfiguration: the server could not find the requested resource
E0502 21:36:13.356046       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.0/tools/cache/reflector.go:167: Failed to watch *v1beta1.FlowSchema: failed to list *v1beta1.FlowSchema: the server could not find the requested resource
```

**To Reproduce**
Install with the extra role as described in #21 

**Expected behavior**
No errors

**Details (please complete the following information):**
 - Scaleway Cert Manager Webhook version: latest
 - Platform: ?
 - Kubernetes version: 1.29.1

**Additional context**
v1beta1 of flowcontrol has been removed since 1.26, v1 is released since 1.29 or alternatively v1beta3 can be used from 1.26 - 1.29

Since the error occurs in client-go perhaps an update of the go dependency is enough to fix this?

**Comment by Nox-404** [comment]
Can you try using the `v0.1.0` ? (just released it)

**Comment by MathyV** [comment]
I just tried `v0.1.0` and can confirm that all the error messages are gone.
