### ISSUE TITLE
Variabilize durations in PKI certificates

### ISSUE THREAD

**Issue by paulden** [scaleway/cert-manager-webhook-scaleway#4]
Hello,

Thanks for your work on this webhook!

**Is your feature request related to a problem? Please describe.**
I am using this webhook to generate certificates on domain names managed on Scaleway. This is deployed using ArgoCD which auto-syncs applications, in this case the chart provided in `deploy/scaleway-webhook` and the durations provided in the PKI is non-standard, causing a constant diff (and thus a constant re-sync):

![Capture du 2021-04-21 12-24-09](https://user-images.githubusercontent.com/22522526/115539304-191f9f00-a29d-11eb-91b5-b73dd97e792f.png)

**Describe the solution you'd like**
I suggest we could variabilize the durations so that clients may use whatever format seems fine to them. Additional benefit is that clients may choose other durations instead of the default ones suggested.

**Describe alternatives you've considered**
I haven't thought of any but I'm open to suggestions.

**Additional context**
I am creating a PR associated with the issue, I'm open to suggestions since I do not know if you have standards. Thanks again for your work!

Paul

**Comment by Sh4d1** [comment]
Thanks for raising the issue, and for the quick fix 🎉 😄
