### ISSUE TITLE
Failed to create Order: 400 urn:ietf:params:acme:error:malformed: No Key ID in JWS header

### ISSUE THREAD

**Issue by basvanbeek** [scaleway/cert-manager-webhook-scaleway#6]
**Describe the bug**
Unable to obtain certificates due to JWS header error.

Observed error:
```
Events:
  Type     Reason        Age   From          Message
  ----     ------        ----  ----          -------
  Normal   OrderCreated  12m   cert-manager  Created Order resource istio-system/**REDACTED**-26kl8-2320222416
  Normal   OrderPending  12m   cert-manager  Waiting on certificate issuance from order istio-system/**REDACTED**-26kl8-2320222416: ""
  Warning  OrderFailed   12m   cert-manager  Failed to wait for order resource "**REDACTED**-26kl8-2320222416" to become ready: order is in "errored" state: Failed to create Order: 400 urn:ietf:params:acme:error:malformed: No Key ID in JWS header
```

I have cert-manager installed in the `cert-manager` namespace, Istio in `istio-system` and I need to use `ClusterIssuer` resources as our apps are in various namespaces (we don't use `default` namespace for deployments).

The cert manager webhook was installed according to latest readme and using default credentials provisioning at install time.

 - Scaleway Cert Manager Webhook version: latest (git clone install flow)
 - Platform: Amazon EKS
 - Kubernetes version: v1.18.9-eks

**Comment by Sh4d1** [comment]
Hey @basvanbeek ! Never seen this issue 🤔 could you share the whole config (cluster issuer, config, ...) ? I'll try to reproduce

**Comment by Nox-404** [comment]
Since there's been no response since June 2021, I'll close that issue.
Feel free to reopen if you need further assistance.
