### ISSUE TITLE
kubectl only procedure

### ISSUE THREAD

**Issue by rhanka** [scaleway/cert-manager-webhook-scaleway#7]
**Is your feature request related to a problem? Please describe.**
Using helm is heaving and lacks of auditability and adaptability to security parameters - rbac...

**Describe the solution you'd like**
I'd like a kubectl deployment alternative for this cert-manager to allow.

**Describe alternatives you've considered**
Recoding webhook by myself, using other cert webooks:
- https://raw.githubusercontent.com/pragkent/alidns-webhook/master/deploy/bundle.yaml
- https://github.com/linka-cloud/k8s-dns-manager
mixed with this:
- https://particule.io/blog/scaleway-externaldns/

**Additional context**

**Comment by Nox-404** [comment]
There's now a bundle in the `deploy` folder.
(default install in the cert-manager namespace)
